# Task 5
### Viviana Aguilar

In [7]:
import math



In [2]:
math.sqrt(25)



5.0

In [3]:
math.pi



3.141592653589793

In [4]:
import math as mt



In [5]:
mt.sqrt(25)



5.0

In [59]:
import numpy
from numpy import random
import numpy as np
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)

In [60]:
print(dataOne)

[[0.50333974 0.26903668 0.43089012 0.76166564 0.24454196]
 [0.29957411 0.67184837 0.25585758 0.99878229 0.48266398]
 [0.97970552 0.36848137 0.47941901 0.83648736 0.08420559]
 [0.50581385 0.34467624 0.45410717 0.6800651  0.1950506 ]
 [0.14875659 0.30702031 0.57770314 0.75441941 0.31396338]]


In [61]:
np.mean(dataOne)

0.477923004553514

In [62]:
DataOne = random.randint(100, size=(3, 5))

print(DataOne)

[[16 46 95 68 78]
 [30 19 51 24 80]
 [71 54 82 77 23]]


In [63]:
Data2 = random.choice([3, 5, 7, 9])

print(Data2)

5


# Math and Statistics Functions

In [64]:
import numpy as np
np.random.seed (42)
Dato3 =  np.random.random (size = 4)

In [65]:
print(Dato3)

[0.37454012 0.95071431 0.73199394 0.59865848]


In [67]:
heads = Dato3 < 0.5
heads

array([ True, False, False, False])

In [68]:
np.sum (heads)

1

In [69]:
math.prod((2, 8, 7, 7))

784

In [70]:
2 * 8 * 7 * 7

784

In [71]:
math.isqrt(9)

3

In [72]:
math.sqrt(9)

3.0

In [73]:
math.isqrt(15)

3

In [74]:
math.sqrt(15)

3.872983346207417

In [75]:
point_1 = (16, 25, 20)
point_2 = (8, 15, 14)

In [76]:
math.dist(point_1, point_2)

14.142135623730951

In [77]:
math.hypot(*point_1)

35.79106033634656

In [78]:
math.hypot(*point_2)

22.02271554554524

In [79]:
import statistics

In [80]:
data = [9, 3, 2, 1, 1, 2, 7, 9]

In [81]:
statistics.fmean(data)

4.25

In [82]:
statistics.geometric_mean(data)

3.013668912157617

In [83]:
statistics.multimode(data)

[9, 2, 1]

In [84]:
statistics.quantiles(data, n=4)

[1.25, 2.5, 8.5]

### Statistics

In [86]:
import statistics
from timeit import timeit

In [87]:
# Create 10,000 random numbers
data = [random.random() for _ in range(10_000)]

In [89]:
# Measure the time it takes to run mean() and fmean()
t_mean = [timeit("statistics.mean(data)", number=100, globals=globals())for _ in range(30)]
t_fmean = [timeit("statistics.fmean(data)", number=100, globals=globals())for _ in range(30)]

In [90]:
# Create NormalDist objects based on the sampled timings
n_mean = statistics.NormalDist.from_samples(t_mean)
n_fmean = statistics.NormalDist.from_samples(t_fmean)

In [92]:
#Look at sample mean and standard deviation
n_mean.mean, n_mean.stdev

(0.5535710183001054, 0.012806397871015208)

In [93]:
n_fmean.mean, n_fmean.stdev

(0.015879518833329106, 9.006993976596276e-05)

In [94]:
# Calculate the lower 1 percentile of mean
n_mean.quantiles(n=100)[0]

0.523778881838748

# Functions and Variables

In [95]:
variableName = 25
variableName1 = 'I Love data Science'
print(variableName1)

I Love data Science


### Ejemplo1

In [96]:
variableName = 25
type(variableName)

int

In [97]:
variableName = 25.0
type(variableName)

float

In [98]:
varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)

50.0


### Ejemplo 2

In [105]:
varOne = 25
varTwo = 'Hello'
varThree = (varTwo + "" + str(varOne))
# Al ser variables diferentes str e int, se debe convertir  el número en texto

print(varThree) 

Hello25


## Lists and Dictionaries

In [107]:
listOne = [1,2,3,4]
print(listOne[1:3])

[2, 3]


In [108]:
print(listOne[0:2])

[1, 2]


In [109]:
tel = {'jack': 4098, 'sape': 4139}
tel['jack']

4098

## Ejercicios propios

### Unión de 2 sets

In [110]:
A={1,2,3,4,5}
B={2,4,6,8}
print (A.union(B))
print (A|B)

{1, 2, 3, 4, 5, 6, 8}
{1, 2, 3, 4, 5, 6, 8}


### Unión de más de 3 sets

In [113]:
A={1,2,3,4,5}
B={2,4,6,8,10}
C={1,3,5,7,9}
print (A|B|C)
print (A.union(B,C))

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


#### Difference between the union() method and the | operator:
union(): It’ll accept any iterable as an argument

| operator: It’ll accept only a set as an argument. Otherwise, it’ll raise a TypeError.

## Intersection of datas

In [114]:
A={1,2,3,4,5}
B={2,4,6,8}
#intersection is performed by intersection() method or & operator
print (A.intersection(B))
print (A&B)

{2, 4}
{2, 4}


In [115]:
A={1,2,3,4,5}
B={2,4,6,8,10}
C={2,4}
print (A&B&C)
print (A.intersection(B,C))

{2, 4}
{2, 4}


Difference between the intersection() method and the & operator:

intersection(): It’ll accept any iterable as an argument

& operator: It’ll accept only a set as an argument. Otherwise, it’ll raise a TypeError.

### Math in Python

In [116]:
a = 88
b = 103

print(a + b)

191


In [117]:
c = -36
d = 25

print(c + d)

-11


In [118]:
e = 5.5
f = 2.5

print(e + f)

8.0


In [119]:
g = 75.67
h = 32

print(g - h)

43.67


### Multiplicarion and Division

In [120]:
k = 100.1
l = 10.1

print(k * l)

1011.0099999999999


In [121]:
m = 80
n = 5

print(m / n)

16.0


In [123]:
m = 80.5
n = 5.4

print(m // n)

14.0


### Modulo
The % operator is the modulo, which returns the remainder rather than the quotient after division. This is useful for finding numbers that are multiples of the same number

In [125]:
o = 85
p = 15

print(o % p)

10


### Power
The ** operator in Python is used to raise the number on the left to the power of the exponent of the right. That is, in the expression 5 ** 3, 5 is being raised to the 3rd power. In mathematics, we often see this expression rendered as 5³, and what is really going on is 5 is being multiplied by itself 3 times. In Python, we would get the same result of 125 by running either 5 ** 3 or 5 * 5 * 5.

In [126]:
s = 52.25
t = 7

print(s ** t)

1063173305051.292


In [128]:
u = 10 + 10 * 5
print(u)

60


### Assignment Operators

In [129]:
w = 5
w += 1
print(w)

6


In [130]:
for x in range (0, 7):
    x *= 2
    print(x)

0
2
4
6
8
10
12


## Important
y += 1          # add then assign value

y -= 1          # subtract then assign value

y *= 2          # multiply then assign value

y /= 3          # divide then assign value

y // = 5        # floor divide then assign value

y **= 2         # increase to the power of then assign value

y %= 3          # return remainder then assign value